CREATE TABLE card (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    card_number VARCHAR(16) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
